# ------------------------------------------------------------
# ⚙️ Netlify Configuration File — Parax 3D Portfolio
# ------------------------------------------------------------

[build]
  publish = "."
  command = ""

# Optional: redirect all clean URLs to HTML pages
[[redirects]]
  from = "/projects"
  to = "/projects.html"
  status = 200
[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200
[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Security headers applied globally
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; media-src 'self' blob:; frame-ancestors 'none'; object-src 'none';"
    Cross-Origin-Resource-Policy = "same-origin"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cache-Control = "no-store, no-cache, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
